version: "3.8"

services:
  db:
    image: postgres:13
    container_name: db
    build: .
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d testdb -U test" ]
      interval: 10s
      timeout: 5s
      retries: 5
