CREATE TABLE CARD (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    SURNAME VARCHAR(30) NOT NULL,
    CARD_NUMBER VARCHAR(16) NOT NULL UNIQUE,
    EXPIRATION_MONTH VARCHAR(2) NOT NULL,
    EXPIRATION_YEAR VARCHAR(4) NOT NULL,
    TYPE_ID BIGINT NOT NULL REFERENCES CARD_TYPE(ID)
);
